name: Clang-Tidy Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy-18
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-18

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=clang++-18
          -DCMAKE_C_COMPILER=clang-18
          -DCMAKE_BUILD_TYPE=Debug
          -DNUMSIM_CAS_BUILD_TESTS=OFF
          -DNUMSIM_CAS_BUILD_EXAMPLES=OFF

      - name: Run clang-tidy
        run: |
          find src -name '*.cpp' -print0 \
          | xargs -0 clang-tidy-18 -p build
